version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - prestashop-net

  prestashop:
    image: prestashop/prestashop:1.7
    environment:
      DB_SERVER: mysql
      DB_NAME: prestashop
      DB_USER: prestashop
      DB_PASSWORD: prestashop
    ports:
      - "8080:80"
    volumes:
      - ./modules:/var/www/html/modules
      - ./themes:/var/www/html/themes
      - ./override:/var/www/html/override
    depends_on:
      - mysql
    networks:
      - prestashop-net

volumes:
  db_data:

networks:
  prestashop-net:
